### ISSUE TITLE
Not possible to use repo tool behind firewall that blocks git://

### ISSUE THREAD

**Issue by ghost** [Xilinx/yocto-manifests#1]
See description, if your firewall blocks git:// and only allows http:// it is not possible to use the repo tool to pull down the repositories. I have tried the replace git:// but http:// trick in .gitconfig but this does not work and some things appear to be hard coded to use git://

**Comment by Livius90** [comment]
In most of company, internal-network proxy server is not configured to use git://.
Please Xilinx, can you use https:// for all git urls in all Xilinx manifest and projects in github?
It could be helpfully to me and many other employee in any other company.

Example:
Use https://github.com/xilinx instead of git://github.com/xilinx and do the same in many other urls, please.

**Comment by Livius90** [comment]
Why did you close this issue? There are no any fix yet!
Pls use the following in default.xml files instead of git:// in your yocto-manifests repo.

```xml
<remote name="xilinx"  fetch="https://github.com/xilinx"/>
```

**Comment by ckalluri73** [comment]
I apologize I thought I posted a comment here before closing the issue. I have pushed a manifest file to our master branch, that does use https over git:// 
I wont be able to change the manifest file for the other already released branches. However all future releases will use https:// over git://
